version: "3"
services:
  
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "8082:8082"
      - "8083:8083"

  consumer-service:
    container_name: consumer-service
    build:
      context: consumer-service
    image: consumer-service
    environment:
      kafkaURL: kafka:9092
      topic: jan-topic
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  producer-service:
    container_name: producer-service
    build:
      context: producer-service
    image: producer-service
    environment:
      kafkaURL: kafka:9092
      topic: jan-topic
    ports:
      - "8001:8001"
    depends_on:
      - kafka
