kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ADVERTISED_PORT
          value: "30718"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
#        - name: KAFKA_BROKER_ID
#          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: jan-topic:1:1
        - name: KAFKA_CONNECT_INTERNAL_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: KAFKA_CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "0"
        - name: KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "0"
        - name: KAFKA_CONNECT_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "0"
        - name: KAFKA_CONNECT_OFFSET_FLUSH_INTERVAL_MS
          value: "10000"
        - name: KAFKA_CONNECT_OFFSET_STORAGE_FILE_FILENAME
          value: /tmp/connect.offsets
        - name: KAFKA_CONNECT_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "0"